global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: onomy-testnet2-val1
    static_configs:
      - targets: ['144.126.222.34:9090']