global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
 - "deploy/config/rules.yaml"
# - "second.rules"

scrape_configs:
  - job_name: onomy-testnet2-val1
    static_configs:
      - targets: ['144.126.222.34:9100']
  - job_name: onomy-testnet2-val2
    static_configs:
      - targets: ['143.110.153.5:9100']


# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - localhost:9093